[pytest]
# Direktori root untuk resolving import
pythonpath = .

# Lokasi test
testpaths = tests

# Tampilkan output lebih detail
addopts = -v --tb=short

# Pola file test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
